repos:
  - repo: https://github.com/ambv/black
    rev: 18.6b4
    hooks:
      - id: black
        language_version: python3.6
        # override until resolved: https://github.com/ambv/black/issues/402
        files: \.pyi?$
        exclude: >
            (?x)^(
            )$

        types: []

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v1.4.0
    hooks:
      - id: flake8
